data:
  raw_dir: "/root/nguyen/research/ML/Final/raw/images" 
  processed_dir: "dataset/processed"
  augmented_dir: "dataset/augmented"
  image_size: 224
  batch_size: 512
  num_workers: 4

  val_size: 0.1  
  test_size: 0.082
  random_state: 42

  stratify: true

model:
  name: "emsac_cap"  # resnet, emsac_cap, emsac
  num_classes: 7
  pretrained: false
  dropout_rate: 0.5
  hidden_size: 512
  learning_rate: 0.001
  weight_decay: 0.0001
  momentum: 0.9

  # if model is emsac_cap
  n_channels: 3
  conv_outputs: 256 #Feature_map
  num_primary_units: 8
  primary_unit_size: 1152 # 32*6*6 fixme get from conv2d
  output_unit_size: 16
  img_size: 299
  init_weights: true
  mode: '256'
    
training:
  epochs: 50
  save_interval: 100 
  log_interval: 20 
  plot_interval: 5
  plots_dir: 'plots' 
  logs_dir: 'logs'
  checkpoint_dir: "checkpoints"
  early_stopping_patience: 5
  use_class_weights: true
  criterion: 'margin'  # Options: 'cross_entropy', 'margin', 'combined'
  metrics_interval: 100
  # Optional settings for margin loss
  margin_loss:
    m_plus: 0.9
    m_minus: 0.1
    lambda: 0.5
    
  # Optional settings for combined loss
  combined_loss:
    margin_weight: 1.0
    ce_weight: 0.2
    m_plus: 0.9
    m_minus: 0.1
    lambda: 0.5


optimizer:
  name: "adam"  # options: adam, sgd
  learning_rate: 0.001
  weight_decay: 0.0001
  momentum: 0.9  # only for SGD

scheduler:
  name: "reduce_on_plateau"  # options: reduce_on_plateau, cosine
  factor: 0.1
  patience: 3
  min_lr: 1e-6

augmentation:
  target_samples: 2000
  rotate_limit: 45
  brightness_contrast_limit: 0.2
  use_color_augmentation: true
  use_noise_augmentation: true
  min_visibility: 0.8
  scale_limit: 0.1

paths:
  metadata: "/root/nguyen/research/ML/Final/raw/GroundTruth.csv"
  train_metadata: "dataset/processed/train_metadata.csv"
  test_metadata: "dataset/processed/test_metadata.csv"
  augmented_metadata: "dataset/processed/augmented_metadata.csv"

  # for another dataset
  mode: "folder" # csv
  root_path: "dataset"

logging:
  log_dir: "logs"
  level: "INFO"

visualization:
  output_dir: "visualizations"
  dpi: 300
  figure_formats: ["png", "pdf"]
  style: "seaborn"

data_analysis:
  min_samples_per_class: 1000
  target_aspect_ratio: 1.0
  image_size_analysis: true
  plot_examples: true
  examples_per_class: 5